# Generated by Django 3.1 on 2020-10-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('kind', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('currency', models.CharField(max_length=3)),
                ('max_attendee_count', models.IntegerField()),
                ('main_image', models.FilePathField()),
                ('description', models.TextField()),
                ('registrable_time', models.DateTimeField(null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
